### ISSUE TITLE
New Bug...

### ISSUE THREAD

**Issue by GitAlex55555** [JordanSantiagoYT/FNF-JS-Engine-Rewrite#5] opened 2024-10-14 07:22 UTC
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

For some reason. Whenever I open a week/level, It gives me an object null refrence!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

Yes

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment] 2024-10-14 09:58
1. wrong repository
2. duplicate of https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/559, also be sure to see https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/359 and https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/576

(since you might be trying on 1.32.0/newer, go to Options, enter the Visuals & UI menu to reset your note splash/skin settings to defaults, then try again.

If it still crashes, then you're missing a required config file for your game to work. Head to the Note Splash Editor by pressing 7 in the main menu, then entering the Note Splash Debug Editor and create one for your skin.)

**Closed as not planned by JordanSantiagoYT** 2024-10-14 09:58 UTC
Labels: bug, duplicate
